FROM node:20-alpine

ARG BUILD_ENV=production
ENV NODE_ENV=$BUILD_ENV

WORKDIR /api

COPY package*.json ./
RUN npm install


RUN echo "Ambiente de build: $BUILD_ENV"

CMD ["npm", "run", "dev"]
