FROM node:20

ARG BUILD_ENV=production
ENV NODE_ENV=$BUILD_ENV

RUN echo "Ambiente de build: $BUILD_ENV"

RUN mkdir -p /api
WORKDIR /api

RUN apt-get update && apt-get install -y \
    python3 python3-venv \
    python3-pip netcat-openbsd make g++ \
    && rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /venv

COPY requirements.txt .

RUN /venv/bin/pip install --no-cache-dir -r requirements.txt

ENV PATH="/venv/bin:$PATH"

COPY pricing/ /api/pricing

COPY package*.json ./
COPY tsconfig.json ./

COPY wait-for-it.sh ./
RUN chmod +x wait-for-it.sh

RUN npm install

COPY . .

EXPOSE 4001

CMD sh -c "./wait-for-it.sh data_eucatur 5432 -- npm run migration:run && npm run dev"